#!/usr/bin/env python3
"""
auto_short_pipeline.py
Minimal automated pipeline:
1) (optional) script generation via OpenAI
2) TTS via gTTS
3) Download a Pexels video clip
4) Combine clip + audio into a vertical Short using ffmpeg
5) (optional) Upload to YouTube (OAuth2 + YouTube Data API)

Before running:
- Install ffmpeg and ensure `ffmpeg` is in PATH.
- pip install -r requirements.txt (see below)
- Create a Pexels API key and set PEXELS_API_KEY in environment or config below.
- (Optional) Create OpenAI API key and set OPENAI_API_KEY if you want better scripts.
- (Optional) For YouTube upload: create OAuth2 credentials and save client_secrets.json, see instructions below.

This script is intentionally simple and synchronous so you can run it locally and inspect outputs.
"""

from __future__ import annotations
import os
import sys
import json
import time
import logging
import shutil
import tempfile
import subprocess
from typing import Optional
from pathlib import Path

import requests
#from gtts import gTTS
from gtts import gTTS

# Optional imports for OpenAI and YouTube:
try:
    import openai
except Exception:
    openai = None

try:
    # Google API client libraries for YouTube upload
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from google.auth.transport.requests import Request
    import google.oauth2.credentials
    import pickle
except Exception:
    # We'll check later and provide helpful error messages if upload is attempted.
    InstalledAppFlow = None
    build = None
    MediaFileUpload = None

# ----------------------------
# CONFIG - fill or set via env
# ----------------------------
# Pexels API (required for automatic clip downloads)
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY", "")  # <- set this
# Optional OpenAI API key - for better script generation
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")  # <- optional
# YouTube upload (optional)
CLIENT_SECRETS_FILE = os.getenv("YOUTUBE_CLIENT_SECRETS_FILE", "client_secrets.json")
YOUTUBE_TOKEN_FILE = os.getenv("YOUTUBE_TOKEN_FILE", "youtube_token.pickle")

# Output folder
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

# ----------------------------
# Helper functions
# ----------------------------

def generate_short_script(topic: str, max_seconds: int = 40) -> str:
    """
    Generate a ~30 second short script. If OPENAI_API_KEY is set and openai package is available,
    uses OpenAI's API. Otherwise, falls back to a lightweight built-in template generator.
    """
    if OPENAI_API_KEY and openai:
        try:
            openai.api_key = OPENAI_API_KEY
            logger.info("Generating script via OpenAI...")
            prompt = (
                f"Write a short, punchy YouTube Short script about: {topic}\n"
                f"Requirements: <= {max_seconds} seconds spoken (approx 60-90 words), "
                "hook in first 3 words, simple sentence structure, call-to-action at end."
            )
            # using ChatCompletion (gpt-3.5) style for portability
            completion = openai.ChatCompletion.create(
                model="gpt-4o-mini" if "gpt-4o-mini" in openai.Model.list().__str__() else "gpt-4o-mini",
                messages=[{"role":"user","content":prompt}],
                max_tokens=180,
                temperature=0.7,
            )
            text = completion["choices"][0]["message"]["content"].strip()
            logger.info("Script generated by OpenAI.")
            return text
        except Exception as e:
            logger.warning("OpenAI generation failed, falling back to local generator. Error: %s", e)

    # fallback
    logger.info("Using fallback local script generator.")
    template = (
        f"Here's a quick tip about {topic}. "
        "First, remember this main idea: focus on one small step. "
        "Next, try this action right now: pause, open your notes, and write down one thing you can do in 10 minutes. "
        "If you want more tips like this, follow for daily shorts!"
    )
    return template


def tts_save_gtts(text: str, out_mp3: Path, lang: str = "en") -> None:
    """Convert text -> mp3 using gTTS (free)."""
    logger.info("Creating TTS audio (gTTS)...")
    try:
        tts = gTTS(text=text, lang=lang)
        tts.save(str(out_mp3))
        logger.info("Saved TTS to %s", out_mp3)
    except Exception as e:
        logger.exception("gTTS failed: %s", e)
        raise


def search_pexels_video(query: str, per_page: int = 5) -> Optional[dict]:
    """Search Pexels videos and return the best-fit video metadata (or None)."""
    if not PEXELS_API_KEY:
        raise RuntimeError("PEXELS_API_KEY not set. Get a free key at https://www.pexels.com/api/")
    headers = {"Authorization": PEXELS_API_KEY}
    params = {"query": query, "per_page": per_page}
    url = "https://api.pexels.com/videos/search"
    logger.info("Searching Pexels for query: %s", query)
    r = requests.get(url, headers=headers, params=params, timeout=20)
    r.raise_for_status()
    data = r.json()
    videos = data.get("videos", [])
    if not videos:
        logger.warning("No videos found for query: %s", query)
        return None
    # Pick video with highest duration <= 60s if possible, otherwise first
    for v in videos:
        if v.get("duration", 999) <= 60:
            logger.info("Selected video id=%s duration=%s", v.get("id"), v.get("duration"))
            return v
    logger.info("Falling back to first video.")
    return videos[0]


def download_pexels_video(video_meta: dict, dest_path: Path) -> Path:
    """Download the first available video file (highest quality) from Pexels video metadata."""
    video_files = video_meta.get("video_files", [])
    if not video_files:
        raise RuntimeError("Pexels video metadata contains no video_files.")
    # Prefer mp4 & bigger width
    video_files_sorted = sorted(video_files, key=lambda f: (f.get("width", 0), f.get("fps", 0)), reverse=True)
    best = video_files_sorted[0]
    video_url = best.get("link")
    if not video_url:
        raise RuntimeError("No downloadable link found in video file metadata.")
    logger.info("Downloading Pexels video from %s ...", video_url)
    with requests.get(video_url, stream=True, timeout=60) as r:
        r.raise_for_status()
        with open(dest_path, "wb") as f:
            shutil.copyfileobj(r.raw, f)
    logger.info("Downloaded video to %s", dest_path)
    return dest_path


def make_vertical_short(input_video: Path, input_audio: Path, output_video: Path, target_width: int = 1080, target_height: int = 1920) -> None:
    """
    Use ffmpeg to:
    - scale input video to target width (maintain aspect) and pad to vertical (1080x1920)
    - add audio and encode to mp4
    Requires ffmpeg in PATH.
    """
    logger.info("Creating vertical short via ffmpeg...")
    if not shutil.which("ffmpeg"):
        raise RuntimeError("ffmpeg not found in PATH. Install ffmpeg and try again.")
    # build ffmpeg command
    # scale to width, then pad vertically to target size centered
    cmd = [
        "ffmpeg", "-y",
        "-i", str(input_video),
        "-i", str(input_audio),
        "-filter_complex",
        f"[0:v]scale={target_width}:-2,setsar=1,pad={target_width}:{target_height}:(ow-iw)/2:(oh-ih)/2:black[v]",
        "-map", "[v]",
        "-map", "1:a",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "128k",
        "-shortest",
        str(output_video)
    ]
    logger.debug("ffmpeg command: %s", " ".join(cmd))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        logger.error("ffmpeg failed: %s\nSTDOUT: %s\nSTDERR: %s", proc.returncode, proc.stdout, proc.stderr)
        raise RuntimeError("ffmpeg failed; see log")
    logger.info("Short created at %s", output_video)


# ----------------------------
# YouTube upload
# ----------------------------
YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def build_youtube_service(client_secrets_file: str = CLIENT_SECRETS_FILE, token_file: str = YOUTUBE_TOKEN_FILE):
    if not InstalledAppFlow:
        raise RuntimeError("Google client libraries not installed. Install google-auth-oauthlib and google-api-python-client.")
    creds = None
    if os.path.exists(token_file):
        with open(token_file, "rb") as f:
            creds = pickle.load(f)
    # If no (valid) creds, run OAuth flow
    if not creds or not getattr(creds, "valid", False):
        if creds and getattr(creds, "expired", False) and getattr(creds, "refresh_token", None):
            try:
                creds.refresh(Request())
            except Exception as e:
                logger.warning("Failed to refresh credentials: %s", e)
                creds = None
        if not creds:
            if not os.path.exists(client_secrets_file):
                raise RuntimeError(f"Client secrets file not found at '{client_secrets_file}'. Create OAuth 2.0 credentials and download client_secrets.json.")
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets_file, YOUTUBE_SCOPES)
            creds = flow.run_console()
            # Save token
            with open(token_file, "wb") as f:
                pickle.dump(creds, f)
    service = build("youtube", "v3", credentials=creds)
    return service


def upload_to_youtube(video_file: Path, title: str, description: str, tags: Optional[list[str]] = None, privacy_status: str = "public"):
    """Upload via YouTube Data API (requires OAuth setup)."""
    logger.info("Uploading to YouTube: %s", video_file)
    service = build_youtube_service()
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags or []
        },
        "status": {
            "privacyStatus": privacy_status
        }
    }
    media = MediaFileUpload(str(video_file), chunksize=-1, resumable=True, mimetype="video/*")
    request = service.videos().insert(part="snippet,status", body=body, media_body=media)
    response = None
    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                logger.info("Upload progress: %.2f%%", status.progress() * 100)
        except Exception as e:
            logger.exception("Upload failed: %s", e)
            raise
    logger.info("Upload successful. Video id: %s", response.get("id"))
    return response.get("id")


# ----------------------------
# Main flow
# ----------------------------
def run_pipeline(topic: str, do_upload: bool = False, output_name_prefix: Optional[str] = None):
    output_name_prefix = output_name_prefix or topic.replace(" ", "_")[:30]
    tmpdir = Path(tempfile.mkdtemp(prefix="short_pipeline_"))
    try:
        # 1) Generate script
        script_text = generate_short_script(topic)
        logger.info("Script: %s", script_text)

        # 2) TTS -> mp3
        audio_file = tmpdir / f"{output_name_prefix}.mp3"
        tts_save_gtts(script_text, audio_file)

        # 3) Find and download a Pexels clip
        video_meta = search_pexels_video(topic)
        if not video_meta:
            raise RuntimeError("No suitable video found on Pexels for topic: " + topic)
        input_video = tmpdir / f"{output_name_prefix}.mp4"
        download_pexels_video(video_meta, input_video)

        # 4) Combine into vertical short
        final_output = OUTPUT_DIR / f"{output_name_prefix}_short.mp4"
        make_vertical_short(input_video, audio_file, final_output)

        # 5) Prepare description with attribution (save license proof)
        desc = f"{topic}\n\nGenerated automatically.\n\nPexels video source: {video_meta.get('url') or video_meta.get('video_files')[0].get('link')}\n"
        # Save local record of metadata and license-like info
        meta_file = OUTPUT_DIR / f"{output_name_prefix}_meta.json"
        with open(meta_file, "w", encoding="utf-8") as f:
            json.dump({"topic": topic, "script": script_text, "pexels_meta": video_meta}, f, indent=2)

        logger.info("Short ready: %s\nMetadata saved: %s", final_output, meta_file)

        # 6) Optional upload
        if do_upload:
            # Check client secrets
            if not os.path.exists(CLIENT_SECRETS_FILE):
                raise RuntimeError(f"You asked to upload, but client secrets file not found: {CLIENT_SECRETS_FILE}")
            yt_title = f"{topic} — quick tip"
            yt_desc = desc + "\nAutomatically generated by pipeline."
            video_id = upload_to_youtube(final_output, yt_title, yt_desc, tags=[topic, "shorts", "automation"])
            logger.info("Uploaded video id: %s", video_id)

        return {"output": str(final_output), "meta": str(meta_file)}
    finally:
        # keep tmp files for debugging by default; remove if you prefer.
        logger.info("Temporary working dir: %s (not removed)", tmpdir)
        # if you want to remove temp dir, uncomment:
        # shutil.rmtree(tmpdir, ignore_errors=True)


# ----------------------------
# Command line interface
# ----------------------------
def print_usage():
    print("""
Usage:
    python auto_short_pipeline.py "topic phrase" [--upload]

Example:
    python auto_short_pipeline.py "AI tools that save time" --upload
""")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)
    topic = sys.argv[1]
    do_upload = "--upload" in sys.argv
    try:
        res = run_pipeline(topic, do_upload)
        logger.info("Pipeline finished OK. Output: %s", res["output"])
    except Exception as e:
        logger.exception("Pipeline failed: %s", e)
        sys.exit(2)
